Add execute until functionality
dbader/schedule pull request #195
Opened 2018-01-25 23:03 UTC by fredthomsen

Add Job.until function which will execute a job until a certain time is
passed.

2018-01-29 08:35 UTC, newbazz commented
Please write the issue reference.

2018-01-29 17:16 UTC, fredthomsen commented
@newbazz partially fulfills #132.

2018-03-31 04:58 UTC, fredthomsen commented
@newbazz or @dbader anything I can do to get this merged in, or is this not desirable?

2021-01-25 04:49 UTC, fredthomsen commented
Bumping this after a few years. @dbader anything I can do here to get this merged in?

2021-02-18 22:19 UTC, SijmenHuizenga requested changes
Thanks for creating this pr! This seems like a good feature to have, and you are on the right track to implement it. Before we get into the code itself, let's take a closer look at the expected behaviour. Let's take this example code:
```
schedule.every(10).seconds.until("23:30").do(job)
while True:
    scheduler.run_pending()
    time.sleep(24)
```
Let's say this code is executed at 23:40. What will happen? I guess in the current implementation the job runs once and is canceled afterwards. Is this expected behaviour?

Another scenario: Let's say above code block starts at 23:29:00. The first execution is at 23:29:24 (scheduled execution was 23:29:10), the second execution is at 23:29:48 (scheduled execution was 23:29:34) and the third execution happens at 23:30:12 (scheduled execution was 23:29:58). At all three the times the job fires. Is this expected behaviour?

Answers to these questions could very well be answered as part of the documentation. 

Let me know if you need help with anything.

2021-02-18 22:19 UTC, SijmenHuizenga commented on schedule/__init__.py
> +        if self.final_run and self.next_run > self.final_run:
I would rather see this check implemented in the `run()` method.

2021-02-18 22:19 UTC, SijmenHuizenga commented on schedule/__init__.py
> +            self.next_run = datetime.datetime.max
If we write this check in the `run()` method, we can return `CancelJob`, which in turn will make the scheduler unschedule the job all together. That way we don't need `datetime.datetime.max`.

2021-02-18 22:19 UTC, SijmenHuizenga commented on test_schedule.py
> +                mock_job).next_run.year == 9999
I think we can add some more test cases here. For example: what would happen if someone enters an invalid date, for example `33:77`?

And we need to add tests to validate that a job is actually canceled after the deadline is reached.

2021-02-18 22:19 UTC, SijmenHuizenga commented on schedule/__init__.py
> +            `YYYY-MM-DD HH:MM` for a different day representing the latest
Should we support second-precision?

2021-02-20 16:14 UTC, fredthomsen commented
Thanks for the review. Been a few years since I did this, I'll get it rebased and address your comments

-------- Original Message --------
On Feb 18, 2021, 17:19, Sijmen wrote:

> @SijmenHuizenga requested changes on this pull request.
>
> Thanks for creating this pr! This seems like a good feature to have, and you are on the right track to implement it. Before we get into the code itself, let's take a closer look at the expected behaviour. Let's take this example code:
>
> schedule.every(10).seconds.until("23:30").do(job)
> while True:
>     scheduler.run_pending()
>     time.sleep(24)
>
> Let's say this code is executed at 23:40. What will happen? I guess in the current implementation the job runs once and is canceled afterwards. Is this expected behaviour?
>
> Another scenario: Let's say above code block starts at 23:29:00. The first execution is at 23:29:24 (scheduled execution was 23:29:10), the second execution is at 23:29:48 (scheduled execution was 23:29:34) and the third execution happens at 23:30:12 (scheduled execution was 23:29:58). At all three the times the job fires. Is this expected behaviour?
>
> Answers to these questions could very well be answered as part of the documentation.
>
> Let me know if you need help with anything.
>
> ---------------------------------------------------------------
>
> In [schedule/__init__.py](https://github.com/dbader/schedule/pull/195#discussion_r578767840):
>
>> @@ -368,6 +369,26 @@ def to(self, latest):
>          self.latest = latest
>          return self
>
> +    def until(self, datetime_str):
>
> It would be nice if this method would accept both a time string and a datetime object. We can detect the difference using [something like this](https://stackoverflow.com/a/16991985/2328729).
>
> ---------------------------------------------------------------
>
> In [schedule/__init__.py](https://github.com/dbader/schedule/pull/195#discussion_r578769957):
>
>> @@ -368,6 +369,26 @@ def to(self, latest):
>          self.latest = latest
>          return self
>
> +    def until(self, datetime_str):
> +        """
> +        Schedule job will run until the specified time string.
> +
> +        :param datetime_str: A string in `HH:MM` format for same day or
> +            `YYYY-MM-DD HH:MM` for a different day representing the latest
> +            time a job can be run
> +        :return: The invoked job instance
> +        """
> +        if ' ' in datetime_str:
>
> Let's add a regular expression check to validate that a valid time format is passed in. See the at() method for an example.
>
> ---------------------------------------------------------------
>
> In [schedule/__init__.py](https://github.com/dbader/schedule/pull/195#discussion_r578770816):
>
>> @@ -179,6 +179,7 @@ def __init__(self, interval, scheduler=None):
>          self.next_run = None  # datetime of the next run
>          self.period = None  # timedelta between runs, only valid for
>          self.start_day = None  # Specific day of the week to start on
> +        self.final_run = None  # optional time of final run
>
> I would prefer naming this variable cancel_after since this value does not indicate an exact moment at which the final run takes place, but rather shows after what timestamp the job is canceled.
>
> ---------------------------------------------------------------
>
> In [schedule/__init__.py](https://github.com/dbader/schedule/pull/195#discussion_r578774002):
>
>> @@ -368,6 +369,26 @@ def to(self, latest):
>          self.latest = latest
>          return self
>
> +    def until(self, datetime_str):
> +        """
> +        Schedule job will run until the specified time string.
> +
> +        :param datetime_str: A string in `HH:MM` format for same day or
>
> Please also add an example in the documentation and add this method in the reference docs.
>
> ---------------------------------------------------------------
>
> In [schedule/__init__.py](https://github.com/dbader/schedule/pull/195#discussion_r578774740):
>
>> @@ -465,6 +486,9 @@ def _schedule_next_run(self):
>              if (self.next_run - datetime.datetime.now()).days >= 7:
>                  self.next_run -= self.period
>
> +        if self.final_run and self.next_run > self.final_run:
>
> I would rather see this check implemented in the run() method.
>
> ---------------------------------------------------------------
>
> In [schedule/__init__.py](https://github.com/dbader/schedule/pull/195#discussion_r578775813):
>
>> @@ -465,6 +486,9 @@ def _schedule_next_run(self):
>              if (self.next_run - datetime.datetime.now()).days >= 7:
>                  self.next_run -= self.period
>
> +        if self.final_run and self.next_run > self.final_run:
> +            self.next_run = datetime.datetime.max
>
> If we write this check in the run() method, we can return CancelJob, which in turn will make the scheduler unschedule the job all together. That way we don't need datetime.datetime.max.
>
> ---------------------------------------------------------------
>
> In [test_schedule.py](https://github.com/dbader/schedule/pull/195#discussion_r578776767):
>
>> @@ -120,6 +120,10 @@ def test_next_run_time(self):
>              assert every().friday.do(mock_job).next_run.day == 8
>              assert every().saturday.do(mock_job).next_run.day == 9
>              assert every().sunday.do(mock_job).next_run.day == 10
> +            assert every().minute.until('12:17').do(
> +                mock_job).next_run.minute == 16
> +            assert every().minute.until('2010-01-06 09:00').do(
> +                mock_job).next_run.year == 9999
>
> I think we can add some more test cases here. For example: what would happen if someone enters an invalid date, for example 33:77?
>
> And we need to add tests to validate that a job is actually canceled after the deadline is reached.
>
> ---------------------------------------------------------------
>
> In [schedule/__init__.py](https://github.com/dbader/schedule/pull/195#discussion_r578779908):
>
>> @@ -368,6 +369,26 @@ def to(self, latest):
>          self.latest = latest
>          return self
>
> +    def until(self, datetime_str):
> +        """
> +        Schedule job will run until the specified time string.
> +
> +        :param datetime_str: A string in `HH:MM` format for same day or
> +            `YYYY-MM-DD HH:MM` for a different day representing the latest
>
> Should we support second-precision?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, [view it on GitHub](https://github.com/dbader/schedule/pull/195#pullrequestreview-593673237), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AAGW3QENIB72UBCJU2ZL7YLS7WHABANCNFSM4ENWP7EA).

2021-02-24 05:16 UTC, fredthomsen commented on schedule/__init__.py
> +        if ' ' in datetime_str:
Doing regex against the timestamp seems more painful and less accurate than just feeding various valid format strings into `datetime.datetime.strptime` and using the first valid one.

2021-02-24 06:04 UTC, fredthomsen commented on schedule/__init__.py
> +            `YYYY-MM-DD HH:MM` for a different day representing the latest
We should.  I'll make this update.

2021-02-25 04:15 UTC, fredthomsen commented on schedule/__init__.py
> +        :param datetime_str: A string in `HH:MM` format for same day or
I have an example, but shouldn't this method's docstring, which I will clean up get auto generated in the docs?

2021-02-25 06:16 UTC, fredthomsen commented
@SijmenHuizenga I've made the updates as requested.

2021-02-28 15:06 UTC, SijmenHuizenga commented on schedule/__init__.py
> +        if ' ' in datetime_str:
Ah yes! Great idea :+1:

2021-02-28 15:07 UTC, SijmenHuizenga commented on schedule/__init__.py
> +        :param datetime_str: A string in `HH:MM` format for same day or
Yes, the docstring will end up in the reference doc. The docstring is meant for detailed description of the working of the method. The examples page is there to show usage in a simpler format using examples. I will update it

2021-02-28 15:21 UTC, SijmenHuizenga commented
You did a great job at this, thanks a lot @fredthomsen! I've just pushed some final touches. Just a summary:

* added support for accepting `datetime.timedelta` and `datetime.time`
* Moved the documentation around a bit. Examples in the rst docs and detailed explanation in the docstring.
* Moved the `convert_str_to_datetime` into its own function `_decode_datetimestr`. We can use that thing in the future to handle decoding for the `.at()` method, but that's a subject for another pr.
* Changed the `run` method to cancel a job when it is about to run and the current moment is after the deadline AND cancel it if the next scheduled timestamp is after the deadline. This way the common rule becomes "The job will never run after the specified deadline". Do you think this logic makes sense?
* Refactored the 'should this be canceled?' into the `_is_overdue` method so that we are able to extend on this when we add 'only run n times'
* Grouped the tests into functional groups.

Let me know if you think this all makes sense!

2021-02-28 15:24 UTC, SijmenHuizenga commented
Well.. Looking at those tests I've got some work to do :sweat_smile:

2021-02-28 15:34 UTC, SijmenHuizenga approved these changes

2021-02-28 16:37 UTC, fredthomsen commented
Yes, I like these changes esp. the checks in `run()`.  Makes more sense that the job can never run after `cancel_after` no matter what.  Just made an additional update to the `until` parameter type hinting.  Looks good to me.

2021-02-28 22:50 UTC, merged