Added documentation regarding corutines
dbader/schedule pull request #391
Opened 2020-10-13 08:04 UTC by 07pepa

* added documentation
* removed trailing spaces

This closes https://github.com/dbader/schedule/issues/388

2020-10-13 08:18 UTC, 07pepa commented
it looks like coverage is buggy...

2021-03-19 22:07 UTC, 07pepa commented
i decided it is not as dependend on #357  and can be fast forwarded

2021-03-19 22:09 UTC, 07pepa commented
@SijmenHuizenga  can we Merge this?... any objections are welcomed :)

2021-03-28 00:02 UTC, SijmenHuizenga requested changes
Thank you for this pr! I learnt some things from it :smile:

The goal of the schedule documentation is to teach people how to use the schedule library. We are not in the business of explaining how asyncio works or state the advantages of using coroutines. 

At the moment the code and text has too many details that are interesting, but not relevant to the schedule docs. I've added some comments to explain my thinking. Let me know if anything is unclear.

During reading and testing I have updated the page to how I see it. I will submit those changes in a separate pr to your branch so that you can decide if you want to include those changes into this pr.

2021-03-30 18:10 UTC, 07pepa commented on docs/async-support.rst
> +.. code-block:: python
agreed

2021-03-30 18:16 UTC, 07pepa commented on docs/async-support.rst
> +Only drawback is precision of asyncio.wait_for timeout.
well i saw some variance in my personal project (few seconds) and real amount of "sleep" is better known for time.sleep https://stackoverflow.com/questions/1133857/how-accurate-is-pythons-time-sleep

so job can be executed later

2021-03-30 18:27 UTC, 07pepa commented on docs/async-support.rst
> +        def terminate(signum):
time sleep and  asyncio sleep are fine on their own

but when you use your custom sigal handler they dont recive KeyboardInterrupt

and if you want your code to finish corectly  you should use them

but in that case you must have something that can be interupted

and you can reference back to issue i created....https://github.com/dbader/schedule/issues/388

i think we should put this as seperate example

2021-04-28 17:39 UTC, 07pepa commented
@SijmenHuizenga  it is better now?

2021-05-22 13:50 UTC, SijmenHuizenga commented
I'm sorry for making you wait this long on a response.

The docs should focus on explaining how the schedule library works and how to use it. The examples about interrupting a loop and handling signals are out of scope. These examples mostly teach the reader about Python and asyncio without teaching much about the schedule library. These examples would fit very well in a blog post or in a Github gist, but not so much in the official docs.

I just pushed the shortened examples and will merge this pr soon.

Thank you for working on these examples, I learnt some new things and I expect many people will too.

2021-05-23 12:29 UTC, closed without merging