Apply black==20.8b1
dbader/schedule pull request #432
Opened 2021-02-07 20:06 UTC by MartinThoma

2021-02-07 22:59 UTC, SijmenHuizenga requested changes
Hi! This looks great. I've added black to the requirements.txt file and added a bit in the documentation. Feel free to make changes to this if you think it can be done better @MartinThoma.

For documentation purposes: this pr has breefly been discussed [here](https://github.com/dbader/schedule/pull/427#discussion_r568936860)

I tried running black on this branch and it formatted the code differently from what is proposed here. I guess running black should result in no changes after this pr. Any idea what could cause this?

2021-02-07 23:21 UTC, SijmenHuizenga commented
And can you add yourself to AUTHORS.rst? Thanks!

2021-02-08 12:49 UTC, MartinThoma commented
@SijmenHuizenga The difference is the only thing that you can configure in black - the line length 😄 

I ran it with "black --line-length 79 ." which is compatible to PEP8. You might have run just "black ." (as in the docs) which by default is a line length of 88 characters. Which line length would you like to have?

I could also add a `pyproject.toml` where the line length is set for black. This way "black ." would do the right thing. You just need to decide what "the right thing" is 😄

2021-02-08 14:41 UTC, MartinThoma reviewed
Adding it to the requirements-dev looks good; the docs might need --line-length

2021-02-08 17:33 UTC, SijmenHuizenga commented
Thanks for the explanation!

Since we are changing the formatting anyway we might as well go with the default black settings :smile: The 88 character line width seems more in line with the rest of the world.

2021-02-08 17:45 UTC, SijmenHuizenga approved these changes
LGTM!

2021-02-08 17:48 UTC, SijmenHuizenga commented
One last thing before we merge, can you please remove the commits that were pulled in from master? Some 'merge' commits are fine but now somehow there are all these commits in here that are unrelated and have you as co-author. If you can't figure out how to fix this git magic, don't worry, just let me know and I will fix it.

2021-02-08 21:53 UTC, MartinThoma commented
I'm sorry, I don't know that. I typically squash before I merge (or amend + force-push on feature branches). If it's not a big deal for you, please go ahead and do it :-)

2021-02-08 21:54 UTC, MartinThoma reviewed
LGTM :+1:

2021-02-09 20:29 UTC, merged